[build]
  command = "ng build --configuration production && gnome-terminal -- bash -c 'npm run json-server; exec bash'"
  publish = "dist/tf_arquiweb"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200
